### PR TITLE
Added light datepicker

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by ThinkGraphical** [comment]
This would be nice if it were to be integrated, the current datepicker annoys me so much.
I always seem to change the date, just by scrolling the page.

**Comment by Piterden** [comment]
I propose to add switcher into preferences section, for each user, even in one Pyro install, could be able to select, which date would be more useful for him privately.

**Comment by RyanThompson** [comment]
Or we could disable scrolling?

**Comment by RyanThompson** [comment]
Date time is a tricky one because of formatting and validation

**Comment by Piterden** [comment]
I could make any formatting for you

**Comment by Piterden** [comment]
With flatpickr we could remove you converter and use only PHP notation of date formatting.
Don't understand about frontend. Where I might be needed? Why can't we use frontend tools for frontend?

Check it self https://chmln.github.io/flatpickr/formatting/

Then it have alternate input which could, not only representing each time different human-readable formats not depends on actual value, but also we could use `parseDate(dateString)` function, which may be used like a guesser of format which user wrote.

And range with multi-date mode.

Inline displaying.

**Comment by mattcdavis1** [comment]
Totally agree with @ThinkGraphical.  We need a datepicker. current date time field is really annoying.

**Comment by Piterden** [comment]
This PR, actually not working cause of that converter. Could we somehow call converter by condition?

**Comment by RyanThompson** [comment]
Added flatpicker manually - good as gold!

**Comment by mattcdavis1** [comment]
nice! I was just about to have to create my own datepicker field type to accomodate client request (unhappy with current date field type).

**Comment by RyanThompson** [comment]
Just in time :-P

**Pull request closed without merging**
