### PR TITLE
Allow for time config to have only one value.

### PR DESCRIPTION
**Pull request by bloveless**

### CODE REVIEW

**Comment by bloveless** [comment]
Related to Issue #1

**Comment by RyanThompson** [comment]
Let's just do this: http://tristan-jahier.fr/blog/2013/08/convertir-un-format-de-date-php-en-format-de-date-jqueryui-datepicker

Have like a DatetimeFieldTypeTransformer class maybe and just do like toPhp($js) and toJs($php)

**Comment by bloveless** [comment]
I like this, because it is very explanatory. toPhp and toJs it much more clear to me than php and plugin.

**Comment by RyanThompson** [comment]
ya and it'll lift restrictions on the devs to provide a weird pipe delimited value.

Ill pry add short, default, long, full as shortcuts to those dropdown options though.

**Pull request closed without merging**
